// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/generativelabs/btcserver/internal/db/ent/globalstate"
	"github.com/generativelabs/btcserver/internal/db/ent/predicate"
)

// GlobalStateDelete is the builder for deleting a GlobalState entity.
type GlobalStateDelete struct {
	config
	hooks    []Hook
	mutation *GlobalStateMutation
}

// Where appends a list predicates to the GlobalStateDelete builder.
func (gsd *GlobalStateDelete) Where(ps ...predicate.GlobalState) *GlobalStateDelete {
	gsd.mutation.Where(ps...)
	return gsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gsd *GlobalStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gsd.sqlExec, gsd.mutation, gsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gsd *GlobalStateDelete) ExecX(ctx context.Context) int {
	n, err := gsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gsd *GlobalStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(globalstate.Table, sqlgraph.NewFieldSpec(globalstate.FieldID, field.TypeInt))
	if ps := gsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gsd.mutation.done = true
	return affected, err
}

// GlobalStateDeleteOne is the builder for deleting a single GlobalState entity.
type GlobalStateDeleteOne struct {
	gsd *GlobalStateDelete
}

// Where appends a list predicates to the GlobalStateDelete builder.
func (gsdo *GlobalStateDeleteOne) Where(ps ...predicate.GlobalState) *GlobalStateDeleteOne {
	gsdo.gsd.mutation.Where(ps...)
	return gsdo
}

// Exec executes the deletion query.
func (gsdo *GlobalStateDeleteOne) Exec(ctx context.Context) error {
	n, err := gsdo.gsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{globalstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gsdo *GlobalStateDeleteOne) ExecX(ctx context.Context) {
	if err := gsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
