// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/generativelabs/btcserver/internal/db/ent/predicate"
	"github.com/generativelabs/btcserver/internal/db/ent/stake"
)

// StakeUpdate is the builder for updating Stake entities.
type StakeUpdate struct {
	config
	hooks    []Hook
	mutation *StakeMutation
}

// Where appends a list predicates to the StakeUpdate builder.
func (su *StakeUpdate) Where(ps ...predicate.Stake) *StakeUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetStaker sets the "Staker" field.
func (su *StakeUpdate) SetStaker(s string) *StakeUpdate {
	su.mutation.SetStaker(s)
	return su
}

// SetNillableStaker sets the "Staker" field if the given value is not nil.
func (su *StakeUpdate) SetNillableStaker(s *string) *StakeUpdate {
	if s != nil {
		su.SetStaker(*s)
	}
	return su
}

// SetStakerPublicKey sets the "StakerPublicKey" field.
func (su *StakeUpdate) SetStakerPublicKey(s string) *StakeUpdate {
	su.mutation.SetStakerPublicKey(s)
	return su
}

// SetNillableStakerPublicKey sets the "StakerPublicKey" field if the given value is not nil.
func (su *StakeUpdate) SetNillableStakerPublicKey(s *string) *StakeUpdate {
	if s != nil {
		su.SetStakerPublicKey(*s)
	}
	return su
}

// SetTx sets the "Tx" field.
func (su *StakeUpdate) SetTx(s string) *StakeUpdate {
	su.mutation.SetTx(s)
	return su
}

// SetNillableTx sets the "Tx" field if the given value is not nil.
func (su *StakeUpdate) SetNillableTx(s *string) *StakeUpdate {
	if s != nil {
		su.SetTx(*s)
	}
	return su
}

// SetStart sets the "Start" field.
func (su *StakeUpdate) SetStart(i int64) *StakeUpdate {
	su.mutation.ResetStart()
	su.mutation.SetStart(i)
	return su
}

// SetNillableStart sets the "Start" field if the given value is not nil.
func (su *StakeUpdate) SetNillableStart(i *int64) *StakeUpdate {
	if i != nil {
		su.SetStart(*i)
	}
	return su
}

// AddStart adds i to the "Start" field.
func (su *StakeUpdate) AddStart(i int64) *StakeUpdate {
	su.mutation.AddStart(i)
	return su
}

// SetDuration sets the "Duration" field.
func (su *StakeUpdate) SetDuration(i int64) *StakeUpdate {
	su.mutation.ResetDuration()
	su.mutation.SetDuration(i)
	return su
}

// SetNillableDuration sets the "Duration" field if the given value is not nil.
func (su *StakeUpdate) SetNillableDuration(i *int64) *StakeUpdate {
	if i != nil {
		su.SetDuration(*i)
	}
	return su
}

// AddDuration adds i to the "Duration" field.
func (su *StakeUpdate) AddDuration(i int64) *StakeUpdate {
	su.mutation.AddDuration(i)
	return su
}

// SetDeadline sets the "Deadline" field.
func (su *StakeUpdate) SetDeadline(i int64) *StakeUpdate {
	su.mutation.ResetDeadline()
	su.mutation.SetDeadline(i)
	return su
}

// SetNillableDeadline sets the "Deadline" field if the given value is not nil.
func (su *StakeUpdate) SetNillableDeadline(i *int64) *StakeUpdate {
	if i != nil {
		su.SetDeadline(*i)
	}
	return su
}

// AddDeadline adds i to the "Deadline" field.
func (su *StakeUpdate) AddDeadline(i int64) *StakeUpdate {
	su.mutation.AddDeadline(i)
	return su
}

// SetReleasingTime sets the "ReleasingTime" field.
func (su *StakeUpdate) SetReleasingTime(i int64) *StakeUpdate {
	su.mutation.ResetReleasingTime()
	su.mutation.SetReleasingTime(i)
	return su
}

// SetNillableReleasingTime sets the "ReleasingTime" field if the given value is not nil.
func (su *StakeUpdate) SetNillableReleasingTime(i *int64) *StakeUpdate {
	if i != nil {
		su.SetReleasingTime(*i)
	}
	return su
}

// AddReleasingTime adds i to the "ReleasingTime" field.
func (su *StakeUpdate) AddReleasingTime(i int64) *StakeUpdate {
	su.mutation.AddReleasingTime(i)
	return su
}

// SetAmount sets the "Amount" field.
func (su *StakeUpdate) SetAmount(u uint64) *StakeUpdate {
	su.mutation.ResetAmount()
	su.mutation.SetAmount(u)
	return su
}

// SetNillableAmount sets the "Amount" field if the given value is not nil.
func (su *StakeUpdate) SetNillableAmount(u *uint64) *StakeUpdate {
	if u != nil {
		su.SetAmount(*u)
	}
	return su
}

// AddAmount adds u to the "Amount" field.
func (su *StakeUpdate) AddAmount(u int64) *StakeUpdate {
	su.mutation.AddAmount(u)
	return su
}

// SetRewardReceiver sets the "RewardReceiver" field.
func (su *StakeUpdate) SetRewardReceiver(s string) *StakeUpdate {
	su.mutation.SetRewardReceiver(s)
	return su
}

// SetNillableRewardReceiver sets the "RewardReceiver" field if the given value is not nil.
func (su *StakeUpdate) SetNillableRewardReceiver(s *string) *StakeUpdate {
	if s != nil {
		su.SetRewardReceiver(*s)
	}
	return su
}

// SetReward sets the "Reward" field.
func (su *StakeUpdate) SetReward(u uint64) *StakeUpdate {
	su.mutation.ResetReward()
	su.mutation.SetReward(u)
	return su
}

// SetNillableReward sets the "Reward" field if the given value is not nil.
func (su *StakeUpdate) SetNillableReward(u *uint64) *StakeUpdate {
	if u != nil {
		su.SetReward(*u)
	}
	return su
}

// AddReward adds u to the "Reward" field.
func (su *StakeUpdate) AddReward(u int64) *StakeUpdate {
	su.mutation.AddReward(u)
	return su
}

// SetFinalizedStatus sets the "FinalizedStatus" field.
func (su *StakeUpdate) SetFinalizedStatus(i int) *StakeUpdate {
	su.mutation.ResetFinalizedStatus()
	su.mutation.SetFinalizedStatus(i)
	return su
}

// SetNillableFinalizedStatus sets the "FinalizedStatus" field if the given value is not nil.
func (su *StakeUpdate) SetNillableFinalizedStatus(i *int) *StakeUpdate {
	if i != nil {
		su.SetFinalizedStatus(*i)
	}
	return su
}

// AddFinalizedStatus adds i to the "FinalizedStatus" field.
func (su *StakeUpdate) AddFinalizedStatus(i int) *StakeUpdate {
	su.mutation.AddFinalizedStatus(i)
	return su
}

// SetReleaseStatus sets the "ReleaseStatus" field.
func (su *StakeUpdate) SetReleaseStatus(i int) *StakeUpdate {
	su.mutation.ResetReleaseStatus()
	su.mutation.SetReleaseStatus(i)
	return su
}

// SetNillableReleaseStatus sets the "ReleaseStatus" field if the given value is not nil.
func (su *StakeUpdate) SetNillableReleaseStatus(i *int) *StakeUpdate {
	if i != nil {
		su.SetReleaseStatus(*i)
	}
	return su
}

// AddReleaseStatus adds i to the "ReleaseStatus" field.
func (su *StakeUpdate) AddReleaseStatus(i int) *StakeUpdate {
	su.mutation.AddReleaseStatus(i)
	return su
}

// SetSubmitStatus sets the "SubmitStatus" field.
func (su *StakeUpdate) SetSubmitStatus(i int) *StakeUpdate {
	su.mutation.ResetSubmitStatus()
	su.mutation.SetSubmitStatus(i)
	return su
}

// SetNillableSubmitStatus sets the "SubmitStatus" field if the given value is not nil.
func (su *StakeUpdate) SetNillableSubmitStatus(i *int) *StakeUpdate {
	if i != nil {
		su.SetSubmitStatus(*i)
	}
	return su
}

// AddSubmitStatus adds i to the "SubmitStatus" field.
func (su *StakeUpdate) AddSubmitStatus(i int) *StakeUpdate {
	su.mutation.AddSubmitStatus(i)
	return su
}

// SetReceiverSig sets the "ReceiverSig" field.
func (su *StakeUpdate) SetReceiverSig(s string) *StakeUpdate {
	su.mutation.SetReceiverSig(s)
	return su
}

// SetNillableReceiverSig sets the "ReceiverSig" field if the given value is not nil.
func (su *StakeUpdate) SetNillableReceiverSig(s *string) *StakeUpdate {
	if s != nil {
		su.SetReceiverSig(*s)
	}
	return su
}

// SetTimestamp sets the "Timestamp" field.
func (su *StakeUpdate) SetTimestamp(i int64) *StakeUpdate {
	su.mutation.ResetTimestamp()
	su.mutation.SetTimestamp(i)
	return su
}

// SetNillableTimestamp sets the "Timestamp" field if the given value is not nil.
func (su *StakeUpdate) SetNillableTimestamp(i *int64) *StakeUpdate {
	if i != nil {
		su.SetTimestamp(*i)
	}
	return su
}

// AddTimestamp adds i to the "Timestamp" field.
func (su *StakeUpdate) AddTimestamp(i int64) *StakeUpdate {
	su.mutation.AddTimestamp(i)
	return su
}

// SetUpdateAt sets the "UpdateAt" field.
func (su *StakeUpdate) SetUpdateAt(i int64) *StakeUpdate {
	su.mutation.ResetUpdateAt()
	su.mutation.SetUpdateAt(i)
	return su
}

// SetNillableUpdateAt sets the "UpdateAt" field if the given value is not nil.
func (su *StakeUpdate) SetNillableUpdateAt(i *int64) *StakeUpdate {
	if i != nil {
		su.SetUpdateAt(*i)
	}
	return su
}

// AddUpdateAt adds i to the "UpdateAt" field.
func (su *StakeUpdate) AddUpdateAt(i int64) *StakeUpdate {
	su.mutation.AddUpdateAt(i)
	return su
}

// Mutation returns the StakeMutation object of the builder.
func (su *StakeUpdate) Mutation() *StakeMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StakeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StakeUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StakeUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StakeUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *StakeUpdate) check() error {
	if v, ok := su.mutation.Staker(); ok {
		if err := stake.StakerValidator(v); err != nil {
			return &ValidationError{Name: "Staker", err: fmt.Errorf(`ent: validator failed for field "Stake.Staker": %w`, err)}
		}
	}
	if v, ok := su.mutation.GetTx(); ok {
		if err := stake.TxValidator(v); err != nil {
			return &ValidationError{Name: "Tx", err: fmt.Errorf(`ent: validator failed for field "Stake.Tx": %w`, err)}
		}
	}
	if v, ok := su.mutation.RewardReceiver(); ok {
		if err := stake.RewardReceiverValidator(v); err != nil {
			return &ValidationError{Name: "RewardReceiver", err: fmt.Errorf(`ent: validator failed for field "Stake.RewardReceiver": %w`, err)}
		}
	}
	return nil
}

func (su *StakeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(stake.Table, stake.Columns, sqlgraph.NewFieldSpec(stake.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Staker(); ok {
		_spec.SetField(stake.FieldStaker, field.TypeString, value)
	}
	if value, ok := su.mutation.StakerPublicKey(); ok {
		_spec.SetField(stake.FieldStakerPublicKey, field.TypeString, value)
	}
	if value, ok := su.mutation.GetTx(); ok {
		_spec.SetField(stake.FieldTx, field.TypeString, value)
	}
	if value, ok := su.mutation.Start(); ok {
		_spec.SetField(stake.FieldStart, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedStart(); ok {
		_spec.AddField(stake.FieldStart, field.TypeInt64, value)
	}
	if value, ok := su.mutation.Duration(); ok {
		_spec.SetField(stake.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedDuration(); ok {
		_spec.AddField(stake.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := su.mutation.Deadline(); ok {
		_spec.SetField(stake.FieldDeadline, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedDeadline(); ok {
		_spec.AddField(stake.FieldDeadline, field.TypeInt64, value)
	}
	if value, ok := su.mutation.ReleasingTime(); ok {
		_spec.SetField(stake.FieldReleasingTime, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedReleasingTime(); ok {
		_spec.AddField(stake.FieldReleasingTime, field.TypeInt64, value)
	}
	if value, ok := su.mutation.Amount(); ok {
		_spec.SetField(stake.FieldAmount, field.TypeUint64, value)
	}
	if value, ok := su.mutation.AddedAmount(); ok {
		_spec.AddField(stake.FieldAmount, field.TypeUint64, value)
	}
	if value, ok := su.mutation.RewardReceiver(); ok {
		_spec.SetField(stake.FieldRewardReceiver, field.TypeString, value)
	}
	if value, ok := su.mutation.Reward(); ok {
		_spec.SetField(stake.FieldReward, field.TypeUint64, value)
	}
	if value, ok := su.mutation.AddedReward(); ok {
		_spec.AddField(stake.FieldReward, field.TypeUint64, value)
	}
	if value, ok := su.mutation.FinalizedStatus(); ok {
		_spec.SetField(stake.FieldFinalizedStatus, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedFinalizedStatus(); ok {
		_spec.AddField(stake.FieldFinalizedStatus, field.TypeInt, value)
	}
	if value, ok := su.mutation.ReleaseStatus(); ok {
		_spec.SetField(stake.FieldReleaseStatus, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedReleaseStatus(); ok {
		_spec.AddField(stake.FieldReleaseStatus, field.TypeInt, value)
	}
	if value, ok := su.mutation.SubmitStatus(); ok {
		_spec.SetField(stake.FieldSubmitStatus, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedSubmitStatus(); ok {
		_spec.AddField(stake.FieldSubmitStatus, field.TypeInt, value)
	}
	if value, ok := su.mutation.ReceiverSig(); ok {
		_spec.SetField(stake.FieldReceiverSig, field.TypeString, value)
	}
	if value, ok := su.mutation.Timestamp(); ok {
		_spec.SetField(stake.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedTimestamp(); ok {
		_spec.AddField(stake.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := su.mutation.UpdateAt(); ok {
		_spec.SetField(stake.FieldUpdateAt, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedUpdateAt(); ok {
		_spec.AddField(stake.FieldUpdateAt, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stake.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StakeUpdateOne is the builder for updating a single Stake entity.
type StakeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StakeMutation
}

// SetStaker sets the "Staker" field.
func (suo *StakeUpdateOne) SetStaker(s string) *StakeUpdateOne {
	suo.mutation.SetStaker(s)
	return suo
}

// SetNillableStaker sets the "Staker" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableStaker(s *string) *StakeUpdateOne {
	if s != nil {
		suo.SetStaker(*s)
	}
	return suo
}

// SetStakerPublicKey sets the "StakerPublicKey" field.
func (suo *StakeUpdateOne) SetStakerPublicKey(s string) *StakeUpdateOne {
	suo.mutation.SetStakerPublicKey(s)
	return suo
}

// SetNillableStakerPublicKey sets the "StakerPublicKey" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableStakerPublicKey(s *string) *StakeUpdateOne {
	if s != nil {
		suo.SetStakerPublicKey(*s)
	}
	return suo
}

// SetTx sets the "Tx" field.
func (suo *StakeUpdateOne) SetTx(s string) *StakeUpdateOne {
	suo.mutation.SetTx(s)
	return suo
}

// SetNillableTx sets the "Tx" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableTx(s *string) *StakeUpdateOne {
	if s != nil {
		suo.SetTx(*s)
	}
	return suo
}

// SetStart sets the "Start" field.
func (suo *StakeUpdateOne) SetStart(i int64) *StakeUpdateOne {
	suo.mutation.ResetStart()
	suo.mutation.SetStart(i)
	return suo
}

// SetNillableStart sets the "Start" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableStart(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetStart(*i)
	}
	return suo
}

// AddStart adds i to the "Start" field.
func (suo *StakeUpdateOne) AddStart(i int64) *StakeUpdateOne {
	suo.mutation.AddStart(i)
	return suo
}

// SetDuration sets the "Duration" field.
func (suo *StakeUpdateOne) SetDuration(i int64) *StakeUpdateOne {
	suo.mutation.ResetDuration()
	suo.mutation.SetDuration(i)
	return suo
}

// SetNillableDuration sets the "Duration" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableDuration(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetDuration(*i)
	}
	return suo
}

// AddDuration adds i to the "Duration" field.
func (suo *StakeUpdateOne) AddDuration(i int64) *StakeUpdateOne {
	suo.mutation.AddDuration(i)
	return suo
}

// SetDeadline sets the "Deadline" field.
func (suo *StakeUpdateOne) SetDeadline(i int64) *StakeUpdateOne {
	suo.mutation.ResetDeadline()
	suo.mutation.SetDeadline(i)
	return suo
}

// SetNillableDeadline sets the "Deadline" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableDeadline(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetDeadline(*i)
	}
	return suo
}

// AddDeadline adds i to the "Deadline" field.
func (suo *StakeUpdateOne) AddDeadline(i int64) *StakeUpdateOne {
	suo.mutation.AddDeadline(i)
	return suo
}

// SetReleasingTime sets the "ReleasingTime" field.
func (suo *StakeUpdateOne) SetReleasingTime(i int64) *StakeUpdateOne {
	suo.mutation.ResetReleasingTime()
	suo.mutation.SetReleasingTime(i)
	return suo
}

// SetNillableReleasingTime sets the "ReleasingTime" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableReleasingTime(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetReleasingTime(*i)
	}
	return suo
}

// AddReleasingTime adds i to the "ReleasingTime" field.
func (suo *StakeUpdateOne) AddReleasingTime(i int64) *StakeUpdateOne {
	suo.mutation.AddReleasingTime(i)
	return suo
}

// SetAmount sets the "Amount" field.
func (suo *StakeUpdateOne) SetAmount(u uint64) *StakeUpdateOne {
	suo.mutation.ResetAmount()
	suo.mutation.SetAmount(u)
	return suo
}

// SetNillableAmount sets the "Amount" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableAmount(u *uint64) *StakeUpdateOne {
	if u != nil {
		suo.SetAmount(*u)
	}
	return suo
}

// AddAmount adds u to the "Amount" field.
func (suo *StakeUpdateOne) AddAmount(u int64) *StakeUpdateOne {
	suo.mutation.AddAmount(u)
	return suo
}

// SetRewardReceiver sets the "RewardReceiver" field.
func (suo *StakeUpdateOne) SetRewardReceiver(s string) *StakeUpdateOne {
	suo.mutation.SetRewardReceiver(s)
	return suo
}

// SetNillableRewardReceiver sets the "RewardReceiver" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableRewardReceiver(s *string) *StakeUpdateOne {
	if s != nil {
		suo.SetRewardReceiver(*s)
	}
	return suo
}

// SetReward sets the "Reward" field.
func (suo *StakeUpdateOne) SetReward(u uint64) *StakeUpdateOne {
	suo.mutation.ResetReward()
	suo.mutation.SetReward(u)
	return suo
}

// SetNillableReward sets the "Reward" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableReward(u *uint64) *StakeUpdateOne {
	if u != nil {
		suo.SetReward(*u)
	}
	return suo
}

// AddReward adds u to the "Reward" field.
func (suo *StakeUpdateOne) AddReward(u int64) *StakeUpdateOne {
	suo.mutation.AddReward(u)
	return suo
}

// SetFinalizedStatus sets the "FinalizedStatus" field.
func (suo *StakeUpdateOne) SetFinalizedStatus(i int) *StakeUpdateOne {
	suo.mutation.ResetFinalizedStatus()
	suo.mutation.SetFinalizedStatus(i)
	return suo
}

// SetNillableFinalizedStatus sets the "FinalizedStatus" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableFinalizedStatus(i *int) *StakeUpdateOne {
	if i != nil {
		suo.SetFinalizedStatus(*i)
	}
	return suo
}

// AddFinalizedStatus adds i to the "FinalizedStatus" field.
func (suo *StakeUpdateOne) AddFinalizedStatus(i int) *StakeUpdateOne {
	suo.mutation.AddFinalizedStatus(i)
	return suo
}

// SetReleaseStatus sets the "ReleaseStatus" field.
func (suo *StakeUpdateOne) SetReleaseStatus(i int) *StakeUpdateOne {
	suo.mutation.ResetReleaseStatus()
	suo.mutation.SetReleaseStatus(i)
	return suo
}

// SetNillableReleaseStatus sets the "ReleaseStatus" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableReleaseStatus(i *int) *StakeUpdateOne {
	if i != nil {
		suo.SetReleaseStatus(*i)
	}
	return suo
}

// AddReleaseStatus adds i to the "ReleaseStatus" field.
func (suo *StakeUpdateOne) AddReleaseStatus(i int) *StakeUpdateOne {
	suo.mutation.AddReleaseStatus(i)
	return suo
}

// SetSubmitStatus sets the "SubmitStatus" field.
func (suo *StakeUpdateOne) SetSubmitStatus(i int) *StakeUpdateOne {
	suo.mutation.ResetSubmitStatus()
	suo.mutation.SetSubmitStatus(i)
	return suo
}

// SetNillableSubmitStatus sets the "SubmitStatus" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableSubmitStatus(i *int) *StakeUpdateOne {
	if i != nil {
		suo.SetSubmitStatus(*i)
	}
	return suo
}

// AddSubmitStatus adds i to the "SubmitStatus" field.
func (suo *StakeUpdateOne) AddSubmitStatus(i int) *StakeUpdateOne {
	suo.mutation.AddSubmitStatus(i)
	return suo
}

// SetReceiverSig sets the "ReceiverSig" field.
func (suo *StakeUpdateOne) SetReceiverSig(s string) *StakeUpdateOne {
	suo.mutation.SetReceiverSig(s)
	return suo
}

// SetNillableReceiverSig sets the "ReceiverSig" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableReceiverSig(s *string) *StakeUpdateOne {
	if s != nil {
		suo.SetReceiverSig(*s)
	}
	return suo
}

// SetTimestamp sets the "Timestamp" field.
func (suo *StakeUpdateOne) SetTimestamp(i int64) *StakeUpdateOne {
	suo.mutation.ResetTimestamp()
	suo.mutation.SetTimestamp(i)
	return suo
}

// SetNillableTimestamp sets the "Timestamp" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableTimestamp(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetTimestamp(*i)
	}
	return suo
}

// AddTimestamp adds i to the "Timestamp" field.
func (suo *StakeUpdateOne) AddTimestamp(i int64) *StakeUpdateOne {
	suo.mutation.AddTimestamp(i)
	return suo
}

// SetUpdateAt sets the "UpdateAt" field.
func (suo *StakeUpdateOne) SetUpdateAt(i int64) *StakeUpdateOne {
	suo.mutation.ResetUpdateAt()
	suo.mutation.SetUpdateAt(i)
	return suo
}

// SetNillableUpdateAt sets the "UpdateAt" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableUpdateAt(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetUpdateAt(*i)
	}
	return suo
}

// AddUpdateAt adds i to the "UpdateAt" field.
func (suo *StakeUpdateOne) AddUpdateAt(i int64) *StakeUpdateOne {
	suo.mutation.AddUpdateAt(i)
	return suo
}

// Mutation returns the StakeMutation object of the builder.
func (suo *StakeUpdateOne) Mutation() *StakeMutation {
	return suo.mutation
}

// Where appends a list predicates to the StakeUpdate builder.
func (suo *StakeUpdateOne) Where(ps ...predicate.Stake) *StakeUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StakeUpdateOne) Select(field string, fields ...string) *StakeUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Stake entity.
func (suo *StakeUpdateOne) Save(ctx context.Context) (*Stake, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StakeUpdateOne) SaveX(ctx context.Context) *Stake {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StakeUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StakeUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *StakeUpdateOne) check() error {
	if v, ok := suo.mutation.Staker(); ok {
		if err := stake.StakerValidator(v); err != nil {
			return &ValidationError{Name: "Staker", err: fmt.Errorf(`ent: validator failed for field "Stake.Staker": %w`, err)}
		}
	}
	if v, ok := suo.mutation.GetTx(); ok {
		if err := stake.TxValidator(v); err != nil {
			return &ValidationError{Name: "Tx", err: fmt.Errorf(`ent: validator failed for field "Stake.Tx": %w`, err)}
		}
	}
	if v, ok := suo.mutation.RewardReceiver(); ok {
		if err := stake.RewardReceiverValidator(v); err != nil {
			return &ValidationError{Name: "RewardReceiver", err: fmt.Errorf(`ent: validator failed for field "Stake.RewardReceiver": %w`, err)}
		}
	}
	return nil
}

func (suo *StakeUpdateOne) sqlSave(ctx context.Context) (_node *Stake, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stake.Table, stake.Columns, sqlgraph.NewFieldSpec(stake.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Stake.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stake.FieldID)
		for _, f := range fields {
			if !stake.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stake.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Staker(); ok {
		_spec.SetField(stake.FieldStaker, field.TypeString, value)
	}
	if value, ok := suo.mutation.StakerPublicKey(); ok {
		_spec.SetField(stake.FieldStakerPublicKey, field.TypeString, value)
	}
	if value, ok := suo.mutation.GetTx(); ok {
		_spec.SetField(stake.FieldTx, field.TypeString, value)
	}
	if value, ok := suo.mutation.Start(); ok {
		_spec.SetField(stake.FieldStart, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedStart(); ok {
		_spec.AddField(stake.FieldStart, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.Duration(); ok {
		_spec.SetField(stake.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedDuration(); ok {
		_spec.AddField(stake.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.Deadline(); ok {
		_spec.SetField(stake.FieldDeadline, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedDeadline(); ok {
		_spec.AddField(stake.FieldDeadline, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.ReleasingTime(); ok {
		_spec.SetField(stake.FieldReleasingTime, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedReleasingTime(); ok {
		_spec.AddField(stake.FieldReleasingTime, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.Amount(); ok {
		_spec.SetField(stake.FieldAmount, field.TypeUint64, value)
	}
	if value, ok := suo.mutation.AddedAmount(); ok {
		_spec.AddField(stake.FieldAmount, field.TypeUint64, value)
	}
	if value, ok := suo.mutation.RewardReceiver(); ok {
		_spec.SetField(stake.FieldRewardReceiver, field.TypeString, value)
	}
	if value, ok := suo.mutation.Reward(); ok {
		_spec.SetField(stake.FieldReward, field.TypeUint64, value)
	}
	if value, ok := suo.mutation.AddedReward(); ok {
		_spec.AddField(stake.FieldReward, field.TypeUint64, value)
	}
	if value, ok := suo.mutation.FinalizedStatus(); ok {
		_spec.SetField(stake.FieldFinalizedStatus, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedFinalizedStatus(); ok {
		_spec.AddField(stake.FieldFinalizedStatus, field.TypeInt, value)
	}
	if value, ok := suo.mutation.ReleaseStatus(); ok {
		_spec.SetField(stake.FieldReleaseStatus, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedReleaseStatus(); ok {
		_spec.AddField(stake.FieldReleaseStatus, field.TypeInt, value)
	}
	if value, ok := suo.mutation.SubmitStatus(); ok {
		_spec.SetField(stake.FieldSubmitStatus, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedSubmitStatus(); ok {
		_spec.AddField(stake.FieldSubmitStatus, field.TypeInt, value)
	}
	if value, ok := suo.mutation.ReceiverSig(); ok {
		_spec.SetField(stake.FieldReceiverSig, field.TypeString, value)
	}
	if value, ok := suo.mutation.Timestamp(); ok {
		_spec.SetField(stake.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedTimestamp(); ok {
		_spec.AddField(stake.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.UpdateAt(); ok {
		_spec.SetField(stake.FieldUpdateAt, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedUpdateAt(); ok {
		_spec.AddField(stake.FieldUpdateAt, field.TypeInt64, value)
	}
	_node = &Stake{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stake.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
