// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GlobalState is the predicate function for globalstate builders.
type GlobalState func(*sql.Selector)

// Stake is the predicate function for stake builders.
type Stake func(*sql.Selector)
