// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StakesColumns holds the columns for the "stakes" table.
	StakesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "staker", Type: field.TypeString, Size: 90},
		{Name: "staker_public_key", Type: field.TypeString},
		{Name: "tx", Type: field.TypeString, Unique: true, Size: 66},
		{Name: "start", Type: field.TypeUint64},
		{Name: "duration", Type: field.TypeUint64},
		{Name: "deadline", Type: field.TypeUint64},
		{Name: "amount", Type: field.TypeUint64},
		{Name: "reward_receiver", Type: field.TypeString, Size: 66},
		{Name: "finalized_status", Type: field.TypeInt, Default: 0},
		{Name: "release_status", Type: field.TypeInt, Default: 0},
		{Name: "btc_sig", Type: field.TypeString},
		{Name: "receiver_sig", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeUint64},
		{Name: "create_at", Type: field.TypeUint64},
		{Name: "update_at", Type: field.TypeUint64},
	}
	// StakesTable holds the schema information for the "stakes" table.
	StakesTable = &schema.Table{
		Name:       "stakes",
		Columns:    StakesColumns,
		PrimaryKey: []*schema.Column{StakesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "stake_staker_tx",
				Unique:  false,
				Columns: []*schema.Column{StakesColumns[1], StakesColumns[3]},
			},
			{
				Name:    "stake_release_status_tx",
				Unique:  false,
				Columns: []*schema.Column{StakesColumns[10], StakesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StakesTable,
	}
)

func init() {
}
